sudo: false
language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"
env:
  - GRAPHQL_VERSION=0.6
  - GRAPHQL_VERSION=0.7
  - GRAPHQL_VERSION=0.8
  - GRAPHQL_VERSION=0.9
  - GRAPHQL_VERSION=latest
install:
  # We need a new version of npm to install babel in such a way that mocha can find it.
  - npm install -g npm@latest
  - npm install graphql@${GRAPHQL_VERSION}
  - npm install
script:
  - npm run lint
  - npm test
