sudo: false
language: node_js
cache: yarn
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
env:
  - GRAPHQL_VERSION=0.6
  - GRAPHQL_VERSION=0.7
  - GRAPHQL_VERSION=0.8
  - GRAPHQL_VERSION=0.9
  - GRAPHQL_VERSION=0.10
  - GRAPHQL_VERSION=latest
install:
  - npm install -g yarn
  - yarn add graphql@${GRAPHQL_VERSION}
  - yarn
script:
  - yarn run lint
  - yarn test
